### ISSUE TITLE
项目打包问题

### ISSUE THREAD

**Issue by schinvendy** [NervJS/taro-ui-sample#2]
目前本地 Taro 版本 为1.1.3
 
文档中说的这个方式，
我测试中该项目打包出来的dist/weapp目录并没有正确打包components目录下的文件
![image](https://user-images.githubusercontent.com/17189558/48194210-53c04600-e387-11e8-869c-2e076bcf8489.png)
![image](https://user-images.githubusercontent.com/17189558/48194277-88340200-e387-11e8-8056-f4af93d69a59.png)

改回原来的导出方式后才能正确打包。

不过这两种方式打包出来的h5目录下都没有index.js文件
![image](https://user-images.githubusercontent.com/17189558/48194433-f7a9f180-e387-11e8-8046-3d316816adb0.png)

dist/index.js需要 module.exports = require('./h5/index')

也就导致运行h5端时候报错了。

**Comment by SzHeJason** [comment]
NervJS/taro#1030

**Comment by schinvendy** [comment]
> [NervJS/taro#1030](https://github.com/NervJS/taro/issues/1030) 建议看下这个
这个解决方法我也提到了。主要是我的打包H5也是有问题的。不知道是个人环境还是taro本身编译问题。

**Comment by SzHeJason** [comment]
config index.js 还有内容

**Comment by schinvendy** [comment]
H5打包错误是windows下打包命令问题，文档中的 TARO_BUILD_TYPE=ui taro build --ui命令在windows环境下无法运行。
所以需要这些写：
CMD中：先 set TARO_BUILD_TYPE=ui 再 taro build --ui
PowerShell中：先 $env:TARO_BUILD_TYPE=“ui“ 再 taro build --ui
